### ISSUE TITLE
list highest relabundance strain when threshold is not met

### ISSUE THREAD

**Issue by TORCH-UAntwerpen** [TORCH-Consortium/MAGMA#101]
Keep track of which strain has the highest relative abundance and list that strain in the qc summary

https://github.com/TORCH-Consortium/xbs-nf/blob/1ff0abfb4b5f641ba75ecd280ce398df749bfa22/bin/quanttb_qc.py#L114

**Comment by abhi18av** [comment]
We've moved away from `QuantTB`
