### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by TORCH-UAntwerpen** [TORCH-Consortium/MAGMA#138]
When setting the memory requirements for the server.conf have to be set in multiple locations. When setting the memory to 6GB in defaultparams.conf, the memory settings in nextflow.conf overrule the memory settings in the default params, maybe we can do something where it takes the minimum of default_params and the process specific settings given in de nextflow.conf. That way the user can specify the maximum amount of memory nextflow can use in the default params.

**Comment by abhi18av** [comment]
Addressed via https://github.com/TORCH-Consortium/MAGMA/issues/77
