### ISSUE TITLE
Add another round of TBProfiler for detection of structural variants 

### ISSUE THREAD

**Issue by vrennie** [TORCH-Consortium/MAGMA#146]
Based on @TimHHH's comments about the ability of TBProfiler to identify and thus report these variants:

"TBprofiler reports look really good in the sense that the large indels are in fact reported, and mostly correct from what I can check."

...

"I think the best compromise is to run TBrofiler on the bam files from MAGMA, because these have been mapped with the strict -k parameter and this will remove lots of mentioned rubbish when present"

@abhi18av I assume that this might require a small  refactor?

**Comment by TimHHH** [comment]
This means the *.dedup_reads.bam would be used as input in TBprofiler. I imagine this would be to be run on a sample by sample basis.

**Comment by abhi18av** [comment]
Hey guys 👋 

Apologies but I'm out of context regarding this conversation. If there's a chance that we connect and take this forward then I'd be happy to put this into shape.

Please feel free to mark the calendar and I'd be there :)
