### ISSUE TITLE
Cleanup output directories

### ISSUE THREAD

**Issue by TimHHH** [TORCH-Consortium/MAGMA#151]
As listed by @vrennie :
```
Reconfiguration of the Output folder

    1. /cohort/minor_variants -> combined_variant_files/ directory is pointless
    2. Delete /libraries/fastq_validation/samples/ 
    3. The /libraries/reports/multiqc needs to moved to /libraries/fastq_validation/fastqc/
    4. /libraries/mapped_sequences/mapped_libraries/ directory is pointless
    5. Delete /QC statistics/sample_thresholds/ 
    6. /samples/major_variants/haplotype_caller/ directory is pointless
 ```

**Comment by TimHHH** [comment]
1. correct, files can be published in /cohort/minor_variants
2. correct
3. makes sense
4. correct, would publish to libraries/mapped_sequence_libraries  or something like that
5. sure
6. ./samples/**variant**_files/major_variants/haplotype_caller, instead I would publish to /samples/variant_files/haplotype_caller_major or something like that
Any other directories that need checking?

**Comment by vrennie** [comment]
Hi @TimHHH how do we change this in the pipeline? Do I make the changes in the develop branch? What's our policy atm?

**Comment by abhi18av** [comment]
Just highlighting that these changes are incoming with #152  and they can be validated here https://github.com/TORCH-Consortium/MAGMA/pull/152/files#diff-f03008ce99218fdb63a3a46827984ebf2cc432b95cafc06f087cc8fb986fe3c1

**Comment by TimHHH** [comment]
> Hi @TimHHH how do we change this in the pipeline? Do I make the changes in the develop branch? What's our policy atm?

Yes I would suggest the develop branch. Publishing a file can be turned on or off with the ```should_publish``` flag in https://github.com/TORCH-Consortium/MAGMA/blob/develop/default_params.config 
This is also where the output directories can be changed.
