### ISSUE TITLE
"Sample has not enough data to estimate library parameters!"

### ISSUE THREAD

**Issue by jloubser** [TORCH-Consortium/MAGMA#155]
If I get this error should I just remove the sample from the samplesheet?
Or is there a way past this and to keep it in to at least get basic mapping/coverage stats but not include it in the ''cohort'' analysis?

**Comment by abhi18av** [comment]
Hi Hanno,

Yes, the `develop` branch has the following option `only_pre_merge_analysis` which would not trigger the `MERGE_WF` analysis.

https://github.com/TORCH-Consortium/MAGMA/blob/9c0fd8f23249fd2009682bb3617a0d73f828b670/main.nf#L28


Also, reference here #152
