### ISSUE TITLE
Update to TBProfiler database

### ISSUE THREAD

**Issue by LennertVerboven** [TORCH-Consortium/MAGMA#159]
I have made an update to the resistance database used by TBProfiler and replaced the resistance_db_who.dr.json file with a new version. The old file can still be found at resistance_db_who.dr.json.bck

This means that you need to recreate the conda environments or at least run the following commands from within the conda_envs folder after downloading the new file. I only made this change to the master branch, so if you are running a different branch, you will need to update the file manually

```
conda activate "./magma-env-1"

echo "INFO: Make a local copy and cd inside it"
cp -r ../resources/resistance_db_who ./
cd resistance_db_who

echo "INFO: Load the database within tb-profiler"
tb-profiler load_library resistance_db_who

echo "INFO: Remove the local copy of the database folder"
cd ..
rm -rf resistance_db_who

echo "INFO: Deactivate the magma-env-1 env"
conda deactivate
```

https://github.com/TORCH-Consortium/MAGMA/blob/f5bd8719afb1fc0a3fb0512b9034f62811d4bb19/resources/resistance_db_who/resistance_db_who.dr.json

@abhi18av I guess this also means you have to update the docker/singularity containers used for AWS

**Comment by abhi18av** [comment]
Sure Lennert, I have addressed it with #152
