### ISSUE TITLE
Structural variants workflow only on samples that passed QC

### ISSUE THREAD

**Issue by LennertVerboven** [TORCH-Consortium/MAGMA#171]
@abhi18av @TimHHH 

https://github.com/TORCH-Consortium/MAGMA/blob/b218fb6fec3444e8e862fa57c04b9efd23944b50/main.nf#L63

The structural variant workflow should only be run for samples that passed QC as delly crashes if your sample has less than 10K mapped reads

**Comment by TimHHH** [comment]
I am glad you figured that one out 👍
